### PR TITLE
Modified to use math.js as processor for input

### PR DESCRIPTION
**Pull request by ericman314**

### CODE REVIEW

**Comment by cryptomanxxx** [comment]
Thanks for taking time to try to help me. I will study your provided code closely to see what I can learn from it. As of now I am only getting an empty list [ ] when I call 7+5; etc but I will try to solve that problem.

**Comment by ericman314** [comment]
Ah, that might be because the math.js parser is expecting a second statement after the `;` on the same line, and since there isn't one, an empty list is returned for some reason? Anyway, the `;` is not required at the end of a statement in Javascript or math.js. If you leave off the `;` it should work.

Another route you might be interested in is [node.js](https://nodejs.org). It's Javascript without a browser or HTML. It's a popular choice for server apps and it might suit your needs.

**Comment by cryptomanxxx** [comment]
Thank you I will try your suggestion. You are a very helpful guy! As a newbie to JavaScript this help is invaluable. This was actually my first pull request. So thank you for that. I am still learning JavaScript and how github works. JavaScript is definetly better than to waste time on proprietary software for sure.  

In regards to node.js I am not very comfortable turning my surface tablet into a server. I think that is what node.js does but I am not 100% sure. I have had another computer (I suspect) attacked this way. It ran 100% disk all the time. I had open an wifi router port. I will however check out node.js again.

**Comment by ericman314** [comment]
I'm not sure about tablets (I don't have one) but on a desktop, node.js just runs in a separate window. It doesn't turn your computer into a server. You _can_ however run a server with it. It's very popular right now and there's a big community behind it, so it should be easy to find examples of whatever particular setup you'd like to do. Good luck!

**Comment by cryptomanxxx** [comment]
hey @ericman314 please check out my updated JavaScript web code editor. Pretty cool don't you think? There is a minor problem with colon notation (hides output). The colon notation for an revaluated input (for example you put in 5+5 and press enter and then you go back and put in 5+5:) does not work. I will try to fix this in the future. The colon notation works for new inputs though. 

I must say that I think my JavaScript webeditor is better than math notepad's (math.js) because a user can easily add their own functions, previous workspaces can be stored and loaded from a local hardrive and my JavaScript webeditor is open source. There is also no monetarization (no adds that math notepad has on their website) and no copyright that again math.js has.

**Pull request merged**
